BradEwing/InfestedArtosis

src/main/java/unit/UnitManager.java, src/main/java/unit/scout/ScoutManager.java, src/main/java/unit/squad/SquadManager.java
fix: consider hostile static defense in fight simulation
=> refactor: unit management around squads encapsulated in SquadManager

src/main/java/Bot.java, src/main/java/info/InformationManager.java, src/main/java/unit/UnitManager.java, src/main/java/unit/squad/SquadManager.java
fix: don't scout base locations of enemy building location known
=> feat: track enemy last known locations

src/main/java/macro/ProductionManager.java
=> - fix production deadlocks

src/main/java/info/ResourceCount.java, src/main/java/macro/ProductionManager.java, src/main/java/unit/WorkerManager.java
- increase expected drone count
- track reserved larva in resource count
- only schedule unit if larva is available
=> macro fixes

src/main/java/planner/PlannedItem.java, src/main/java/unit/managed/ManagedUnit.java, src/main/java/unit/squad/Squad.java
If I'm stepping on your toes, feel free to reject this. I was just browsing and noticed.
=> closes #45

src/main/java/info/BaseData.java, src/main/java/info/GameState.java, src/main/java/info/InformationManager.java, src/main/java/macro/ProductionManager.java, src/main/java/planner/Plan.java, src/main/java/planner/PlanComparator.java, src/main/java/strategy/StrategyManager.java, src/main/java/strategy/openers/FivePool.java, src/main/java/strategy/openers/FourPool.java, src/main/java/strategy/openers/NinePoolSpeed.java, src/main/java/strategy/openers/Opener.java, src/main/java/strategy/openers/OverPool.java, src/main/java/strategy/openers/TwelveHatch.java, src/main/java/strategy/strategies/Strategy.java, src/main/java/unit/BuildingManager.java, src/main/java/unit/WorkerManager.java, src/main/java/unit/managed/ManagedUnit.java, src/main/java/unit/managed/ManagedUnitInterface.java
refactor: plannedItem renamed to plan
=> fix: reclaim reserved resources when a plan is cancelled 

src/main/java/info/BaseData.java, src/main/java/info/GameState.java, src/main/java/info/InformationManager.java, src/main/java/macro/ProductionManager.java, src/main/java/planner/Plan.java, src/main/java/planner/PlanComparator.java, src/main/java/strategy/StrategyManager.java, src/main/java/strategy/openers/FivePool.java, src/main/java/strategy/openers/FourPool.java, src/main/java/strategy/openers/NinePoolSpeed.java, src/main/java/strategy/openers/Opener.java, src/main/java/strategy/openers/OverPool.java, src/main/java/strategy/openers/TwelveHatch.java, src/main/java/strategy/strategies/Strategy.java, src/main/java/unit/BuildingManager.java, src/main/java/unit/WorkerManager.java, src/main/java/unit/managed/ManagedUnit.java, src/main/java/unit/managed/ManagedUnitInterface.java
fix: cancel scheduled plans on worker death
refactor: PlannedItem -> Plan
=> fix: unreserve a base if assigned worker is killed while plan is scheduled 

src/main/java/info/BaseData.java, src/main/java/info/InformationManager.java, src/main/java/unit/squad/SquadManager.java
- Track natural expansion
- Rally to natural after hatchery is complete
=> feat: iterate on squad rally points 

src/main/java/info/BaseData.java, src/main/java/info/ResourceCount.java, src/main/java/info/map/GameMap.java, src/main/java/info/map/ScoutPath.java, src/main/java/unit/UnitManager.java, src/main/java/unit/scout/ScoutManager.java
=> feature: drone continues to scout base until attacked

src/main/java/macro/ProductionManager.java, src/main/java/strategy/OpenerFactory.java, src/main/java/strategy/openers/NineHatchInBase.java, src/main/java/strategy/openers/NinePool.java, src/main/java/strategy/openers/OpenerName.java, src/main/java/unit/BuildingManager.java
fix: don't make multiple lairs
=> feature: 9PoolInBase (vs Z) and 9Pool (vs P/R)

src/main/java/learning/OpenerRecord.java, src/main/java/learning/StrategyRecord.java
Exploration term and default value reduced
=> feature: adjust bandit index calculations

src/main/java/Bot.java, src/main/java/info/InformationManager.java, src/main/java/unit/UnitManager.java, src/main/java/unit/managed/ManagedUnit.java, src/main/java/unit/managed/UnitRole.java, src/main/java/unit/scout/ScoutManager.java, src/main/java/unit/squad/Squad.java, src/main/java/unit/squad/SquadManager.java, src/main/java/util/Stats.java
refactor: assign ManagedUnit fight target in squad manager
=> feat: mutalisk focus fire

src/main/java/unit/managed/Drone.java, src/main/java/unit/managed/Hydralisk.java, src/main/java/unit/managed/ManagedUnit.java
refactor: updateState() in ManagedUnit
=> feat: hydralisk micro improvements

src/main/java/unit/managed/Lurker.java, src/main/java/unit/managed/ManagedUnit.java, src/main/java/unit/squad/Squad.java
feat(Squad): disable regrouping
=> feat(Lurker): don't unburrow if closer fight targets exist

src/main/java/config/Config.java, src/main/java/learning/LearningManager.java, src/main/java/unit/managed/ManagedUnit.java, src/main/java/unit/managed/Mutalisk.java, src/main/java/unit/managed/Zergling.java
feat: override openeder
feat: zerglings attack position, default attack fightTarget
=> feat: add mutalisk target priority

src/main/java/info/GameState.java, src/main/java/macro/ProductionManager.java, src/main/java/strategy/v2/Legacy.java, src/main/java/strategy/v2/Strategy.java
- wip v2.Strategy class
- prepare to extract unit planning into strategy, consuming GameState
- cleanup ProductionManager
- add util method to get Time from GameState
=> feat: scaffold v2.Strategy impl

src/main/java/Debug.java, src/main/java/info/map/BuildingPlanner.java, src/main/java/strategy/buildorder/opener/NinePoolSpeed.java, src/main/java/unit/squad/SquadManager.java
change: muta squad threshold 5 -> 4
feat: creeptiles exclude geyser bbox
=> fix: 9PoolSpeed places pool.

src/main/java/info/map/BuildingPlanner.java, src/main/java/learning/LearningManager.java, src/main/java/learning/OpponentRecord.java
fix: guard against NPE in geyser bbox
refactor: cleanup OpponentRecord, remove deprecated fields
=> feat: version OpponentRecord

src/main/java/info/InformationManager.java, src/main/java/info/tracking/ObservedUnit.java, src/main/java/info/tracking/ObservedUnitTracker.java, src/main/java/info/tracking/protoss/CannonRush.java, src/main/java/info/tracking/terran/TerranBaseStrategy.java, src/main/java/info/tracking/terran/TwoRaxAcademy.java, src/main/java/strategy/buildorder/protoss/ProtossBase.java, src/main/java/strategy/buildorder/protoss/ThreeHatchMuta.java
feat: method to detect if building is proxied
feat: adjust gas timing and zergling count for cannon rush
=> feat(StrategyTracker): detect cannon rush

src/main/java/info/GameState.java, src/main/java/info/map/BuildingPlanner.java, src/main/java/strategy/buildorder/BuildOrder.java, src/main/java/strategy/buildorder/terran/TerranBase.java
feat: more aggressive sunken reactions in ZvT
=> fix: resolve conflicting BuildingPlanner reservations
